- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset0"

  isEnabled: true

  selectedDataEntry: "Random15PercentRealData"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Random15Percent/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst250403_WithTrackSplit_BNBFixedProb.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "( IsData ? (Run<9300 ? 0.17351986877866 : 0.141261182170497) : (3.5670840e+19/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight ) )"

  data:
    - name: "Random15PercentRealData"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "(IsRandom15Percent ? 1.0 : 0.0)"
      filePathList:
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run1.root"
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run2.root"

- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset1"

  isEnabled: true

  selectedDataEntry: "Random15PercentRealData"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Random15Percent/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst250403_WithTrackSplit_BNBFixedProb.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "( IsData ? (Run<9300 ? 0.17351986877866 : 0.141261182170497) : (3.5670840e+19/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight ) )"

  data:
    - name: "Random15PercentRealData"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "(IsRandom15Percent ? 1.0 : 0.0)"
      filePathList:
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run1.root"
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run2.root"
