- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset0"

  isEnabled: true

  selectedDataEntry: "RealDataForSideband_FakeDataForSignal"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (2.500616E+20/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG3Chase * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) ) : ( IsData ? (Run<9300 ? 1.26862061947009 : 0.984613145608233) : (2.500616E+20/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG3Chase * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) )"

  data:
    - name: "RealDataForSideband_FakeDataForSignal"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (2.500616E+20/2.4783646e+20)  * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG3Chase * SPPQ2RW * SPPTpiMINERvAFittedReweight * 1.) ) : ( IsData ? (1.) : (0.) )"
      filePathList:
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/240729_NuMIReproc_TrackSplitShift/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run1.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/240729_NuMIReproc_TrackSplitShift/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run2.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24_115Files.root"

- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset1"

  isEnabled: true

  selectedDataEntry: "RealDataForSideband_FakeDataForSignal"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (2.500616E+20/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG3Chase * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) ) : ( IsData ? (Run<9300 ? 1.26862061947009 : 0.984613145608233) : (2.500616E+20/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG3Chase * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) )"

  data:
    - name: "RealDataForSideband_FakeDataForSignal"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (2.500616E+20/2.4783646e+20)  * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG3Chase * SPPQ2RW * SPPTpiMINERvAFittedReweight * 1.) ) : ( IsData ? (1.) : (0.) )"
      filePathList:
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/240729_NuMIReproc_TrackSplitShift/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run1.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/240729_NuMIReproc_TrackSplitShift/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run2.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24_115Files.root"
