- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset0"

  isEnabled: true

  selectedDataEntry: "RealDataForSideband_FakeDataForSignal"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst250403_WithTrackSplit_BNBFixedProb.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "CutType==1 ? (IsData ? (0.) : (2.500616E+20/1.0900766e+21) * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight) : (IsData ? (Run<9300 ? 1.26862061947009 : 0.984613145608233) : (2.500616E+20/1.0900766e+21) * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight)"

  data:
    - name: "RealDataForSideband_FakeDataForSignal"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "CutType==1 ? (IsData ? (0.) : (2.500616E+20/2.5029729e+20) * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight) : (IsData ? (1.) : (0.))"
      filePathList:
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run1.root"
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run2.root"
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst250403_WithTrackSplit_BNBFixedProb_115Files.root"

- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset1"

  isEnabled: true

  selectedDataEntry: "RealDataForSideband_FakeDataForSignal"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst250403_WithTrackSplit_BNBFixedProb.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/Originals/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "CutType==1 ? (IsData ? (0.) : (2.500616E+20/1.0900766e+21) * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight) : (IsData ? (Run<9300 ? 1.26862061947009 : 0.984613145608233) : (2.500616E+20/1.0900766e+21) * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight)"

  data:
    - name: "RealDataForSideband_FakeDataForSignal"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "CutType==1 ? (IsData ? (0.) : (2.500616E+20/2.5029729e+20) * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithBeamWidthCorrection * SPPQ2RW * SPPTpiMINERvAFittedReweight) * POTWeightedTriggerWeight) : (IsData ? (1.) : (0.))"
      filePathList:
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run1.root"
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Run2.root"
        - "${GUNDAM_TREE_DIR}/${GUNDAM_INPUT_JOBNAME}/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst250403_WithTrackSplit_BNBFixedProb_115Files.root"