- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset0"

  isEnabled: true

  selectedDataEntry: "Random15PercentRealDataForSideband_FakeDataForSignal"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (3.5670840e+19/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG4Update * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) ) : ( IsData ? (Run<9300 ? 0.17351986877866 : 0.141261182170497) : (3.5670840e+19/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG4Update * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) )"

  data:
    # - 19Aug: POT=2.4783646e+20 POT
    # - 02Oct: POT=2.4993316e+20 POT
    # - 11Oct: POT=2.5029729e+20 POT
    - name: "Random15PercentRealDataForSideband_FakeDataForSignal"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (3.5670840e+19/2.5029729e+20)  * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG4Update * SPPQ2RW * SPPTpiMINERvAFittedReweight * 1.) ) : ( IsData ? (1.) : (0.) )"
      filePathList:
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/241111_PreparingSignalUnboxing/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Overlapping15Percent_Run1.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/241111_PreparingSignalUnboxing/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Overlapping15Percent_Run2.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24_115Files.root"

- name: "ICARUSNuMI_1muNp0pi_Reco_Dataset1"

  isEnabled: true

  selectedDataEntry: "Random15PercentRealDataForSideband_FakeDataForSignal"

  showSelectedEventCount: true

  mc:
    tree: "AllSamples_FillTree/selectedEvents_NSigmas"
    filePathList:
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run1.root"
      - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_Data_OffBeamNUMIMAJORITY_2023ANuMIReproc_Run2.root"
    nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (3.5670840e+19/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG4Update * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) ) : ( IsData ? (Run<9300 ? 0.17351986877866 : 0.141261182170497) : (3.5670840e+19/1.0900766e+21) * ( (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG4Update * SPPQ2RW * SPPTpiMINERvAFittedReweight) ) )"

  data:
    # - 19Aug: POT=2.4783646e+20 POT
    # - 02Oct: POT=2.4993316e+20 POT
    # - 11Oct: POT=2.5029729e+20 POT
    - name: "Random15PercentRealDataForSideband_FakeDataForSignal"
      tree: "AllSamples_FillTree/selectedEvents"
      nominalWeightFormula: "CutType==1 ? ( IsData ? (0.) : (3.5670840e+19/2.5029729e+20)  * (IsSignal==5 ? 0.67937750173924 : FluxWeightWithG4Update * SPPQ2RW * SPPTpiMINERvAFittedReweight * 1.) ) : ( IsData ? (1.) : (0.) )"
      filePathList:
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/241111_PreparingSignalUnboxing/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Overlapping15Percent_Run1.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/NuMINumuXSec/NuMIPyAna/EventSelectionPlots/inputfiles/241111_PreparingSignalUnboxing/rootfiles/MakeTree_Data_NuMIMAJORITY_2023ANuMIReproc_Overlapping15Percent_Run2.root"
        - "/Users/jskim/Documents/Neutrino/ICARUS/GUNDAM-1.9.X/work/rootfiles/241111_PreparingSignalUnboxing/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24_115Files.root"
