
name: Template Parameter TruedeltaalphaT
isEnabled: true

printDialSetsSummary: true

nominalStepSize: 0.1
useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: Template Parameter TruedeltaalphaT dialSetDefinitions
    applyOnDataSets: [ "ICARUSNuMI_1muNp0pi_Reco_Dataset0", "ICARUSNuMI_1muNp0pi_True_Dataset0" ]
    parametersBinningPath: "./inputs/binnings/binning_TruedeltaalphaT.txt"
    applyCondition: "[IsSignal] == 1"
    printDialsSummary: true


