
name: Template Parameter TruedeltaPT
isEnabled: true

printDialSetsSummary: true

nominalStepSize: 1
useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: Template Parameter TruedeltaPT dialSetDefinitions
    applyOnDataSets: [ "ICARUSNuMI_1muNp0pi_Reco_Dataset0", "ICARUSNuMI_1muNp0pi_True_Dataset0" ]
    parametersBinningPath: "./inputs/binnings/binning_TruedeltaPT.txt"
    applyCondition: "[IsSignal] == 1"
    printDialsSummary: true


