# Config for gundamFitter: starting based on screenshots on sbn-doc-32028... let's see

outputFolder: "./output_CalcXsec/"
minGundamVersion: 1.9.0

xsecCalcConfig:
  enableStatThrowInToys: true
  enableEventMcThrow: true

fitterEngineConfig:

  # minimizer
  minimizerConfig: "./Configs_Minimizer/default_minimizer.yaml"

  # likelihoodInterface
  likelihoodInterfaceConfig:

    # jointProbability
    jointProbabilityConfig:
      type: "PoissonLLH"

    # dataSetManager
    propagatorConfig:
      # use --fitsample-config to update
      fitSampleSetConfig: "./Configs_FitSampleSet/fitSamples_TruedeltaPT.yaml"
      parametersManagerConfig:
        parameterSetList: "./Configs_ParameterSetList/parameterSetList_deltaPT.yaml"

    dataSetList: "./Configs_DataSetList/dataSetListConfig_True.yaml"

    # use --plot-config to update
    plotGeneratorConfig: "./Configs_PlotGenerator/plotConfigs_TruedeltaPT.yaml"

