parametersManagerConfig:
  parameterSetList: "./Configs_ParameterSetList/FSIOnly/parameterSetList_deltaPT_and_deltaalphaT.yaml"

showEventBreakdown: true

enableStatThrowInToys: false

enableEventMcThrow: false

debugPrintLoadedEvents: true

fitSampleSetConfig: "./Configs_FitSampleSet/fitSamples_RecodeltaPT_and_RecodeltaalphaT_2DSideband.yaml"

plotGeneratorConfig: "./Configs_PlotGenerator/plotConfigs_RecodeltaPT_and_RecodeltaalphaT.yaml"

