varDictionnaries:
  - name: "IsSignal"
    dictionary:
      - { value: 5, title: "Cosmic", color: 805 } # kMagenta
      - { value: 4, title: "NuNC", color: 866 } # kRed
      - { value: 3, title: "NuCCOther", color: 842 } # kGreen+2
      - { value: 2, title: "OOPS", color: 800 } # kOrange
      - { value: 1, title: "signal", color: 855 } # kOrange

histogramsDefinition:
  - varToPlot: "RecoProtonCos"
    splitVars: ["IsSignal"]
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_RecoProtonCos.txt"
    rescaleAsBinWidth: false
    xTitle: "cos(#theta_{p})"
    yTitle: "Slices"

canvasParameters:
  height: 800
  width: 1000
  nbXplots: 1
  nbYplots: 1
