

parameterSetList:

  # Template parameters
  - "inputs/propagator/parameters/template/configTemplateParameters_TruedeltaalphaT.yaml"

  # Cross-section models systematics
  - "inputs/propagator/parameters/cross-section/configCrossSectionParameters.yaml"
  - "inputs/propagator/parameters/cross-section/configNucleonFsiSyst_TruedeltaalphaT.yaml"
  - "inputs/propagator/parameters/cross-section/configPionFsiSyst_TruedeltaalphaT.yaml"

  # Reconstruction systematics
  - "inputs/propagator/parameters/detector/configDetectorParameters.yaml"

  # Neutrino flux systematics
  - "inputs/propagator/parameters/flux/configFluxHadronProductionSyst.yaml"
  - "inputs/propagator/parameters/flux/configFluxBeamLineSyst.yaml"

  # Geant4 related
  - "inputs/propagator/parameters/simulation/configGeant4ProtonFateSyst.yaml"
  - "inputs/propagator/parameters/simulation/configGeant4PiPlusFateSyst.yaml"
  - "inputs/propagator/parameters/simulation/configGeant4PiMinusFateSyst.yaml"


