name: Flux Systematics HP
isEnabled: true

printDialSetsSummary: true

allowPca: true

useEigenDecompInFit: false

# covarianceMatrixFilePath: "${GUNDAM_INPUTS_DIR}/Configs_ParameterSet/Flux/2023-07-31_out_450.37_7991.98_79512.66_QEL11.root" # with empty bins
covarianceMatrixFilePath: "${GUNDAM_INPUTS_DIR}/Configs_ParameterSet/Flux/2023-08-17_out_450.37_7991.98_79512.66_QEL11.root" # empty bins removed
covarianceMatrixTMatrixD: "covariance_matrices/hadron/total/cov_total"

parameterLimits:
  minValue: 0
  maxValue: 30

useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: Flux Systematics HP dialSetDefinitions
    applyOnDataSets: ["*"]
    #parametersBinningPath: "${GUNDAM_INPUTS_DIR}/binnings/binning_fluxCovMtx.txt" # with empty bins
    parametersBinningPath: "${GUNDAM_INPUTS_DIR}/binnings/binning_fluxCovMtx_removeHE_jk.txt" # empty bins removed
    printDialsSummary: true
    applyCondition: "[IsData]==0"
