


fitSampleList:

  - name: "SignalSelection_RecodeltaPT"
    isEnabled: true
    binning: "./inputs/binnings/binning_RecodeltaPT.txt"
    selectionCuts: "CutType==1 && MuonTrackType==1"
    dataSets: ["ICARUSNuMI_1muNp0pi_Reco_Dataset0"]

  - name: "Sideband_RecodeltaPT"
    isEnabled: true
    binning: "./inputs/binnings/binning_RecodeltaPT.txt"
    selectionCuts: "CutType==2 && LeadingChargedPionCandidateLength>=10."
    dataSets: ["ICARUSNuMI_1muNp0pi_Reco_Dataset0"]

