# Config for gundamFitter: starting based on screenshots on sbn-doc-32028... let's see

outputFolder: "${GUNDAM_INPUTS_DIR}/output_CalcXsec/"
minGundamVersion: 1.9.0

xsecCalcConfig:
  enableStatThrowInToys: true
  enableEventMcThrow: true

fitterEngineConfig:

  # minimizer
  minimizerConfig: "${GUNDAM_INPUTS_DIR}/Configs_Minimizer/default_minimizer.yaml"

  # likelihoodInterface
  likelihoodInterfaceConfig:

    # jointProbability
    jointProbabilityConfig:
      type: "PoissonLLH"

    # dataSetManager
    propagatorConfig:
      # use --fitsample-config to update
      fitSampleSetConfig: "${GUNDAM_INPUTS_DIR}/Configs_FitSampleSet/fitSamples_TrueMuonCos.yaml"
      parametersManagerConfig:
        parameterSetList: "${GUNDAM_INPUTS_DIR}/Configs_ParameterSetList/FluxHPPCA_FSIMultisigma/parameterSetList_MuonCos.yaml"

    dataSetList: "${GUNDAM_INPUTS_DIR}/Configs_DataSetList/dataSetListConfig_True.yaml"

    # use --plot-config to update
    plotGeneratorConfig: "${GUNDAM_INPUTS_DIR}/Configs_PlotGenerator/plotConfigs_TrueMuonCos.yaml"

