parametersManagerConfig:
  parameterSetList: "./Configs_ParameterSetList/FSIMultisigma/parameterSetList_MuonCos_and_MuonProtonCos.yaml"

showEventBreakdown: true

enableStatThrowInToys: false

enableEventMcThrow: false

debugPrintLoadedEvents: true

fitSampleSetConfig: "./Configs_FitSampleSet/fitSamples_RecoMuonCos_and_RecoMuonProtonCos.yaml"

plotGeneratorConfig: "./Configs_PlotGenerator/plotConfigs_RecoMuonCos_and_RecoMuonProtonCos.yaml"

