

name: FSI pi TruedeltaPT
isEnabled: true

printDialSetsSummary: true

allowPca: true

useEigenDecompInFit: true

covarianceMatrixFilePath: "./CovMat/outputs/output_CovMat_GENIE_fsi_pi_TruedeltaPT.root"
covarianceMatrixTMatrixD: "GENIE_fsi_pi_TruedeltaPT/GENIE_fsi_pi_TruedeltaPT_covariance"

parameterLimits:
  minValue: 0
  maxValue: 30

useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: FSI pi TruedeltaPT dialSetDefinitions
    applyOnDataSets: [ "*" ]
    parametersBinningPath: "./binnings/binning_TruedeltaPT.txt"
    printDialsSummary: true
    applyCondition: "[IsData]==0"

