

name: FSI pi TruedeltaalphaT
isEnabled: true

printDialSetsSummary: true

allowPca: false

useEigenDecompInFit: true

covarianceMatrixFilePath: "./inputs/propagator/parameters/cross-section/matrices/output_CovMat_GENIE_fsi_pi_TruedeltaalphaT.root"
covarianceMatrixTMatrixD: "GENIE_fsi_pi_TruedeltaalphaT/GENIE_fsi_pi_TruedeltaalphaT_covariance"

parameterLimits:
  minValue: 0
  maxValue: 30

useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: FSI pi TruedeltaalphaT dialSetDefinitions
    applyOnDataSets: [ "*" ]
    parametersBinningPath: "./inputs/binnings/binning_TruedeltaalphaT.txt"
    printDialsSummary: true
    applyCondition: "[IsData]==0"

