
name: G4 Piminus Fate
isEnabled: true

printDialSetsSummary: true

allowPca: false

useEigenDecompInFit: false
allowEigenDecompWithBounds: true

covarianceMatrixFilePath: "./inputs/propagator/parameters/simulation/matrices/output_CovMat_G4PimFate.root"
covarianceMatrixTMatrixD: "G4PimFate/G4PimFate_covariance"

parameterLimits:
  minValue: 0
  maxValue: 30

useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: G4 Piminus Fate dialSetDefinitions
    applyOnDataSets: [ "*" ]
    parametersBinningPath: "./inputs/binnings/binning_G4PimFate.txt"
    printDialsSummary: true
    applyCondition: "[IsData]==0"
