
name: G4 Piplus Fate
isEnabled: true

printDialSetsSummary: true

allowPca: true

useEigenDecompInFit: true

covarianceMatrixFilePath: "./CovMat/outputs/output_CovMat_G4PipFate.root"
covarianceMatrixTMatrixD: "G4PipFate/G4PipFate_covariance"

parameterLimits:
  minValue: 0
  maxValue: 30

useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: G4 Piplus Fate dialSetDefinitions
    applyOnDataSets: [ "*" ]
    parametersBinningPath: "./binnings/binning_G4PipFate.txt"
    printDialsSummary: true
    applyCondition: "[IsData]==0"