- name: "ICARUSNuMI_1muNp0pi_True_Dataset0"

  mc:
    tree: "AllSamples_FillTree/trueEvents_NSigmas"
    filePathList:
      - "${GUNDAM_INPUTS_DIR}/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24.root"
    nominalWeightFormula: "(FluxWeightWithG3Chase)"

- name: "ICARUSNuMI_1muNp0pi_True_Dataset1"

  mc:
    tree: "AllSamples_FillTree/trueEvents_NSigmas"
    filePathList:
      - "${GUNDAM_INPUTS_DIR}/rootfiles/240729_NuMIReproc_TrackSplitShift/MakeTree_NuMI_MC_Nu_Phase2_2023ANuMIReproc_CAFTypeCommonRemerge_ReNuSyst11Oct24.root"
    nominalWeightFormula: "(FluxWeightWithG3Chase)"

